"""
Diagram generation code for aks_appgw_sql_architecture
Generated by Azure Diagram MCP Server
"""

from diagrams import Diagram, Cluster
from diagrams.azure.network import ApplicationGateway
from diagrams.azure.compute import AKS
from diagrams.azure.database import SQLDatabases
from diagrams.onprem.network import Internet

with Diagram("AKS with Application Gateway and Azure SQL", show=False, filename=r'c:/Users/dminkovski/Development/Microsoft/AzureDiagramMCP/diagrams/aks_appgw_sql_architecture'):
    internet = Internet("Internet")

    with Cluster("Virtual Network"):
        with Cluster("Public Subnet"):
            app_gw = ApplicationGateway("Application Gateway")

        with Cluster("Private Subnet"):
            aks = AKS("AKS Cluster")

        with Cluster("Database Subnet"):
            sql_db = SQLDatabases("Azure SQL Database")

    # Traffic flow
    internet >> app_gw >> aks
    aks >> sql_db

